platform :ios, '8.0'
target "Tenposs" do
pod 'SDWebImage', "~>3.7"
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'SVPullToRefresh'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'TwitterKit', "~>2.2"
pod 'SVProgressHUD'
end