source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target "Tenposs" do
pod 'SDWebImage'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'SVPullToRefresh'
pod 'TwitterKit', "~>2.2"
pod 'SVProgressHUD'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'SVPullToRefresh'
end
