source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target “TenpossStaff” do
pod 'SDWebImage', "~>3.7"
pod 'SVPullToRefresh'
pod 'SVProgressHUD'
pod 'SVPullToRefresh'
end